### ISSUE TITLE
Error upon installation

### ISSUE THREAD

**Issue by pcav** [geometalab/Quiz-QGIS-Plugin#1]
After unzipping in the plugins dir, I get an error:

Questo plugin è corrotto
2

**Comment by DennisLigtenberg** [comment]
Try renaming the plugin dir to Quiz-QGIS-Plugin.

**Comment by pcav** [comment]
Improving, but not quite:

Questo plugin è corrotto
invalid syntax

**Comment by DennisLigtenberg** [comment]
The instalation over the plugin manager works. The problem with the version from the repository is that it has hyphens in the Directory name whitch QGIS does not seem to like. You can ignore this error and activate the plugin, it should work.

**Comment by pcav** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paolo/qgis_test/python/plugins/Quiz-QGIS-Plugin/**init**.py", line 27, in classFactory
    return Quiz(iface)
  File "/home/paolo/qgis_test/python/plugins/Quiz-QGIS-Plugin/quiz.py", line 97, in **init**
    + '/i18n/guitext_de_CH.txt', 'r', 'utf-8')
  File "/usr/lib/python2.7/codecs.py", line 878, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 2] File o directory non esistente: u'/home/paolo/qgis_testpython/plugins/QuizQGISPlugin/i18n/guitext_de_CH.txt'

**Comment by DennisLigtenberg** [comment]
You might have to call the directory QuizQGISPlugin in order for it to work sorry.

**Comment by pcav** [comment]
Renamed, still same error.
Please upload a fixed version.

**Comment by DennisLigtenberg** [comment]
I can't duplicate the bug... After downloading it i renamed the directory to Quiz-QGIS-Plugin and it worked (with the syntac error message though).

**Comment by pcav** [comment]
Sorry, unclear to me: do you imply an user should rename the plugin?

**Comment by DennisLigtenberg** [comment]
It should be fixed now. I can't do anything about the invalid syntax message.

**Comment by pcav** [comment]
Could you please release a new version with the fix so I can test it?
Thanks.
